// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzcdmhmootdzsiteiedh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6Y2RtaG1vb3RkenNpdGVpZWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDA5NDMsImV4cCI6MjA1OTMxNjk0M30.LhKB1zCQLH5WjizgwySSW1qvqqAAYop-D7ZZCnAljdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);